services:
  - type: web
    name: recruitmind-backend
    env: python
    buildCommand: pip install -r requirements.txt && python data/generate_candidates.py
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: recruitmind-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ui/app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: recruitmind-backend
          property: host
